In [1]:
import numpy as np

likes = np.array([120, 250, 180, 340, 500, 275, 410])

print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [2]:
steps = np.array([
    [3000, 5000],
    [4000, 6000],
    [3500, 5500],
    [4500, 6500],
    [5000, 7000]
])

print("Original:")
print(steps)
print("Shape:", steps.shape)

# Convert to 1D
steps_1d = steps.reshape(10)

print("\n1D array:")
print(steps_1d)
print("Shape:", steps_1d.shape)

# Convert back to 2D
steps_2d = steps_1d.reshape(5, 2)

print("\n2D array:")
print(steps_2d)
print("Shape:", steps_2d.shape)

Original:
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 6500]
 [5000 7000]]
Shape: (5, 2)

1D array:
[3000 5000 4000 6000 3500 5500 4500 6500 5000 7000]
Shape: (10,)

2D array:
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 6500]
 [5000 7000]]
Shape: (5, 2)


In [3]:
prices = np.array([
    [250, 180, 320, 150],
    [450, 220, 190, 350],
    [280, 175, 400, 300]
])

print("Original array:")
print(prices)

r = prices.ravel()
print("\nRavel:")
print(r)

f = prices.flatten()
print("\nFlatten:")
print(f)

prices.resize(4, 3)
print("\nResize:")
print(prices)

Original array:
[[250 180 320 150]
 [450 220 190 350]
 [280 175 400 300]]

Ravel:
[250 180 320 150 450 220 190 350 280 175 400 300]

Flatten:
[250 180 320 150 450 220 190 350 280 175 400 300]

Resize:
[[250 180 320]
 [150 450 220]
 [190 350 280]
 [175 400 300]]


In [4]:
playlist = np.array([
    [10, 5, 8],    # Playlist 1
    [7, 12, 6],    # Playlist 2
    [15, 4, 9]     # Playlist 3
])

print("Original array:")
print(playlist)

# Method 1: Using T
print("\nUsing T:")
print(playlist.T)

# Method 2: Using np.transpose()
print("\nUsing np.transpose():")
print(np.transpose(playlist))

Original array:
[[10  5  8]
 [ 7 12  6]
 [15  4  9]]

Using T:
[[10  7 15]
 [ 5 12  4]
 [ 8  6  9]]

Using np.transpose():
[[10  7 15]
 [ 5 12  4]
 [ 8  6  9]]


In [5]:
ratings = np.array([4, 5, 3, 4, 2, 5, 4, 3, 5, 4, 3, 2, 5, 4, 5])

print("Original 1D array:")
print(ratings)

# Convert 1D array into 3 rows and 5 columns
ratings_3x5 = ratings.reshape(3, 5)

print("\n3x5 array:")
print(ratings_3x5)

# Convert 3x5 array back to 1D
ratings_1d = ratings_3x5.flatten()

print("\nFlattened array:")
print(ratings_1d)


Original 1D array:
[4 5 3 4 2 5 4 3 5 4 3 2 5 4 5]

3x5 array:
[[4 5 3 4 2]
 [5 4 3 5 4]
 [3 2 5 4 5]]

Flattened array:
[4 5 3 4 2 5 4 3 5 4 3 2 5 4 5]
