In [1]:
import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First price:", prices[0])
print("Last price:", prices[-1])


First price: 199
Last price: 599


In [2]:
scores = np.array([
    [45, 60, 72, 80, 55],
    [50, 65, 70, 85, 60],
    [40, 55, 75, 90, 65]
])

# Matches 2 to 4 → index 1 to 3
result = scores[:, 1:4]

print(result)

[[60 72 80]
 [65 70 85]
 [55 75 90]]


In [3]:
ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

print(ratings[-3:])

[2.9 5.  3.5]


In [4]:
numbers = np.arange(1, 21)

result = numbers[1::3]

print(result)

[ 2  5  8 11 14 17 20]


In [5]:
prices = np.array([250, 650, 450, 800, 550, 300, 1000])

result = prices[prices > 500]

print(result)

[ 650  800  550 1000]


In [7]:
scores = np.array([210, 180, 195, 220, 205, 175])

result = np.where(scores > 200)

print(result)

(array([0, 3, 4]),)
