In [2]:
import numpy as np

zomato = np.array([4.5, 4.2, 3.8, 4.7, 4.0])
swiggy = np.array([4.1, 3.9, 4.6, 4.3, 4.8])

ratings = np.concatenate((zomato, swiggy))

print(ratings)

[4.5 4.2 3.8 4.7 4.  4.1 3.9 4.6 4.3 4.8]


In [3]:
post1 = np.array([100, 150, 200, 250, 300, 350, 400])
post2 = np.array([120, 180, 220, 280, 320, 370, 450])
post3 = np.array([90, 140, 190, 240, 290, 330, 380])

weekly_likes = np.vstack((post1, post2, post3))

print(weekly_likes)

[[100 150 200 250 300 350 400]
 [120 180 220 280 320 370 450]
 [ 90 140 190 240 290 330 380]]


In [4]:
product_ids = np.array([
    101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112
])

parts = np.array_split(product_ids, 5)

for part in parts:
    print(part)
    print("Shape:", part.shape)

[101 102 103]
Shape: (3,)
[104 105 106]
Shape: (3,)
[107 108]
Shape: (2,)
[109 110]
Shape: (2,)
[111 112]
Shape: (2,)


In [5]:
# Messages sent by 3 users for 7 days
chat = np.array([
    [20, 15, 25, 10, 18, 22, 30],  # User 1
    [5, 8, 6, 4, 7, 5, 9],         # User 2
    [15, 20, 18, 22, 16, 19, 25]   # User 3
])

# Add a new user
new_user = np.array([10, 12, 15, 8, 11, 14, 13])

chat = np.insert(chat, 3, new_user, axis=0)

print("After adding new user:")
print(chat)

# Find the user with the least total messages
totals = np.sum(chat, axis=1)
least_user = np.argmin(totals)

# Remove that user
chat = np.delete(chat, least_user, axis=0)

print("\nAfter removing least active user:")
print(chat)

After adding new user:
[[20 15 25 10 18 22 30]
 [ 5  8  6  4  7  5  9]
 [15 20 18 22 16 19 25]
 [10 12 15  8 11 14 13]]

After removing least active user:
[[20 15 25 10 18 22 30]
 [15 20 18 22 16 19 25]
 [10 12 15  8 11 14 13]]


In [6]:
views = np.array([1000, 2000, 3000, 4000])

# Create a view and a copy
view = views.view()
copy = views.copy()

# Modify the first element
view[0] = 9999
copy[0] = 8888

print("Original array:", views)
print("View:", view)
print("Copy:", copy)

Original array: [9999 2000 3000 4000]
View: [9999 2000 3000 4000]
Copy: [8888 2000 3000 4000]
